# from https://yutani.rbind.io/post/2017-10-18-circleci/
version: 2.1

defaults: &steps
  steps:
    - checkout

    ## build and test -----------------

    - run:
        name: Install and Test this package
        command: make testcov

jobs:
  "julia-release":
     docker:
       - image: julia:1.5.3

     <<: *steps

  "julia-devel":
     docker:
       - image: julia:1.6.0-rc1
     <<: *steps

workflows:
  version: 2
  build_and_test:
    jobs:
      - "julia-release"
      - "julia-devel"

